[GLOBAL]
pants_version = "2.20.0"
build_file_prelude_globs = ["build-support/pants/macros/*.py"]

backend_packages = [
  "pants.backend.docker",
  "pants.backend.docker.lint.hadolint",
  "pants.backend.python.lint.autoflake",
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.shell",
  "pants.backend.shell.lint.shellcheck",
  "pants.backend.shell.lint.shfmt",
]

[anonymous-telemetry]
enabled = true
repo_id = "B573B56B-6289-40C5-ADB7-4C5FA659EAD1"


[python]
pip_version = "23.3.2"
enable_resolves = true
interpreter_constraints = ["CPython==3.10.*"]
default_resolve = "default"

[python-infer]
use_rust_parser = true


[python.resolves]
default = "3rdparty/py/default.lock"

[python-repos]
find_links = ["file:///tmp/psutil"]

[pex-cli]
version = "v2.1.161"
known_versions = [
  "v2.1.161|macos_arm64 |5bb08a677d309889b3357cd23a3a95945a4c3438cfb00ece5291dcfe89221fcc|3675619",
  "v2.1.161|macos_x86_64|5bb08a677d309889b3357cd23a3a95945a4c3438cfb00ece5291dcfe89221fcc|3675619",
  "v2.1.161|linux_x86_64|5bb08a677d309889b3357cd23a3a95945a4c3438cfb00ece5291dcfe89221fcc|3675619",
  "v2.1.161|linux_arm64 |5bb08a677d309889b3357cd23a3a95945a4c3438cfb00ece5291dcfe89221fcc|3675619",
]

[python.resolves_to_only_binary]
default = ["psutil"]
